# Generated by Django 5.0 on 2024-01-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='subscribed_date',
            new_name='date_subscribed',
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='date_unsubscribed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
